# Generated by Django 5.1.6 on 2025-02-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HomePageContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("about_text", models.TextField(verbose_name="Текст о ресторане")),
                (
                    "about_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="home_images/",
                        verbose_name="Изображение о ресторане",
                    ),
                ),
                ("menu_title", models.CharField(max_length=255, verbose_name="Меню")),
                (
                    "menu_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="home_images/",
                        verbose_name="Меню",
                    ),
                ),
                ("menu_desc", models.TextField(verbose_name="Описание меню")),
                (
                    "events_title",
                    models.CharField(
                        max_length=255, verbose_name="Банкеты и мероприятия"
                    ),
                ),
                (
                    "events_desc",
                    models.TextField(verbose_name="Описание Банкеты и мероприятия"),
                ),
                (
                    "events_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="home_images/",
                        verbose_name="Банкеты и мероприятия",
                    ),
                ),
                (
                    "live_music_title",
                    models.CharField(max_length=255, verbose_name="Живая музыка"),
                ),
                (
                    "live_music_desc",
                    models.TextField(verbose_name="Описание Живая музыка"),
                ),
                (
                    "live_music_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="home_images/",
                        verbose_name="Живая музыка",
                    ),
                ),
                ("address", models.CharField(max_length=255, verbose_name="Адрес")),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "working_hours",
                    models.CharField(max_length=255, verbose_name="График работы"),
                ),
            ],
        ),
    ]
