# Generated by Django 5.1.6 on 2025-02-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepagecontent",
            name="scheme_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="home_images/",
                verbose_name="Схема проезда",
            ),
        ),
    ]
