# Generated by Django 5.1.6 on 2025-03-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_homepagecontent_scheme_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "history_title",
                    models.CharField(max_length=255, verbose_name="История ресторана"),
                ),
                (
                    "history_desc",
                    models.TextField(verbose_name="Описание истории ресторана"),
                ),
                (
                    "history_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="home_images/",
                        verbose_name="История",
                    ),
                ),
                (
                    "mission_title",
                    models.CharField(max_length=255, verbose_name="Миссия и ценности"),
                ),
                (
                    "mission_desc",
                    models.TextField(verbose_name="Описание миссия и ценности"),
                ),
                (
                    "mission_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="home_images/",
                        verbose_name="Миссия",
                    ),
                ),
                (
                    "band_title",
                    models.CharField(max_length=255, verbose_name="Наша команда"),
                ),
                ("band_desc", models.TextField(verbose_name="Описание нашей команды")),
                (
                    "band_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="home_images/",
                        verbose_name="Команда",
                    ),
                ),
            ],
        ),
    ]
