# Generated by Django 5.1.6 on 2025-03-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_aboutcontent"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServicesContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("menu_title", models.CharField(max_length=255, verbose_name="Меню")),
                ("menu_desc", models.TextField(verbose_name="Описание меню")),
                (
                    "menu_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="home_images/",
                        verbose_name="Меню",
                    ),
                ),
                (
                    "events_title",
                    models.CharField(
                        max_length=255, verbose_name="Банкеты и мероприятия"
                    ),
                ),
                (
                    "events_desc",
                    models.TextField(verbose_name="Описание Банкеты и мероприятия"),
                ),
                (
                    "events_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="home_images/",
                        verbose_name="Банкеты и мероприятия",
                    ),
                ),
                (
                    "live_music_title",
                    models.CharField(max_length=255, verbose_name="Живая музыка"),
                ),
                (
                    "live_music_desc",
                    models.TextField(verbose_name="Описание Живая музыка"),
                ),
                (
                    "live_music_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="home_images/",
                        verbose_name="Живая музыка",
                    ),
                ),
            ],
        ),
    ]
